### ISSUE TITLE
Typical-build  does not resolve dependencies

### ISSUE THREAD

**Issue by pravanjan** [gogradle/examples#2]
CFULL385-PRT:typical-build pravanjan$ ./gradlew goBuild 
Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details

> Task :goPrepare 
Use project GOPATH: /Users/pravanjan/gitProject/examples/typical-build/.gogradle/project_gopath
<=------------> 8% EXECUTING [10m 1s]
> :resolveBuildDependencies

As we see its running from the last 10 min does not say anything what's going wrong.

**Comment by blindpirate** [comment]
Can't reproduce on my machine. It's hard to say anything wrong with these information, it would be great if you can provide more information, for example, `jstack` thread dumps.

**Comment by pravanjan** [comment]
```
FULL385-PRT:typical-build pravanjan$ jstack -l 17891
2019-05-27 14:32:37
Full thread dump OpenJDK 64-Bit Server VM (25.212-b03 mixed mode):

"Attach Listener" #20 daemon prio=9 os_prio=31 tid=0x00007fd41f036800 nid=0xf07 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"forward input" #19 prio=5 os_prio=31 tid=0x00007fd41e53d000 nid=0x5907 waiting on condition [0x00007000038b7000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076eb008a8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at org.gradle.util.DisconnectableInputStream.read(DisconnectableInputStream.java:138)
	at org.gradle.launcher.daemon.client.InputForwarder$1.run(InputForwarder.java:77)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- <0x000000076eb00da0> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"DisconnectableInputStream source reader" #18 daemon prio=5 os_prio=31 tid=0x00007fd41e513000 nid=0x5707 runnable [0x0000700003789000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <0x000000076eb121c8> (a java.io.BufferedInputStream)
	at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:96)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None

"process reaper" #14 daemon prio=10 os_prio=31 tid=0x00007fd41da10000 nid=0xa803 runnable [0x00007000037b4000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.UNIXProcess.waitForProcessExit(Native Method)
	at java.lang.UNIXProcess.lambda$initStreams$3(UNIXProcess.java:289)
	at java.lang.UNIXProcess$$Lambda$7/1241928735.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- <0x000000076eb08768> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"pool-1-thread-1" #12 prio=5 os_prio=31 tid=0x00007fd41f29d000 nid=0x5503 waiting on condition [0x0000700003686000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076eb18770> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None

"Service Thread" #9 daemon prio=9 os_prio=31 tid=0x00007fd41f046000 nid=0x4203 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C1 CompilerThread3" #8 daemon prio=9 os_prio=31 tid=0x00007fd41e849000 nid=0x3d03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007fd41e84c800 nid=0x3b03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007fd41f014800 nid=0x3a03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007fd41d80b800 nid=0x3903 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007fd41d80a800 nid=0x4603 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007fd41e847000 nid=0x3603 in Object.wait() [0x0000700002e6e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076eb282f8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	- locked <0x000000076eb282f8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

   Locked ownable synchronizers:
	- None

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007fd41e846800 nid=0x3503 in Object.wait() [0x0000700002d6b000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076eb20770> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x000000076eb20770> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

   Locked ownable synchronizers:
	- None

"main" #1 prio=5 os_prio=31 tid=0x00007fd41e002800 nid=0x2603 runnable [0x000070000234b000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x000000076eb381b0> (a sun.nio.ch.Util$3)
	- locked <0x000000076eb381c0> (a java.util.Collections$UnmodifiableSet)
	- locked <0x000000076eb38160> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketInputStream.read(SocketConnection.java:178)
	at com.esotericsoftware.kryo.io.Input.fill(Input.java:139)
	at com.esotericsoftware.kryo.io.Input.require(Input.java:159)
	at com.esotericsoftware.kryo.io.Input.readInt(Input.java:308)
	at org.gradle.internal.serialize.kryo.KryoBackedDecoder.readSmallInt(KryoBackedDecoder.java:120)
	at org.gradle.internal.serialize.DefaultSerializerRegistry$TaggedTypeSerializer.read(DefaultSerializerRegistry.java:139)
	at org.gradle.internal.serialize.Serializers$StatefulSerializerAdapter$1.read(Serializers.java:36)
	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:79)
	at org.gradle.launcher.daemon.client.DaemonClientConnection.receive(DaemonClientConnection.java:75)
	at org.gradle.launcher.daemon.client.DaemonClientConnection.receive(DaemonClientConnection.java:35)
	at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:210)
	at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:178)
	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:141)
	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:92)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:291)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:264)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:33)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:257)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:191)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

   Locked ownable synchronizers:
	- None

"VM Thread" os_prio=31 tid=0x00007fd41e83f800 nid=0x3303 runnable 

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007fd41e00e800 nid=0x1b07 runnable 

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007fd41e00f000 nid=0x2a03 runnable 

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007fd41e00f800 nid=0x5403 runnable 

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007fd41e010800 nid=0x5303 runnable 

"GC task thread#4 (ParallelGC)" os_prio=31 tid=0x00007fd41e011000 nid=0x2e03 runnable 

"GC task thread#5 (ParallelGC)" os_prio=31 tid=0x00007fd41e011800 nid=0x3003 runnable 

"GC task thread#6 (ParallelGC)" os_prio=31 tid=0x00007fd41e800800 nid=0x5203 runnable 

"GC task thread#7 (ParallelGC)" os_prio=31 tid=0x00007fd41e801800 nid=0x3203 runnable 

"VM Periodic Task Thread" os_prio=31 tid=0x00007fd41f047000 nid=0x4003 waiting on condition 

JNI global references: 263
```

**Comment by blindpirate** [comment]
Can you please put the Gradle daemon JVM's thread dumps? The dumps you pasted seem to be coming from Gradle client JVM. You'd find a JVM process with start command line containing something like `GradleDaemon`.

**Comment by pravanjan** [comment]
FULL385-PRT:typical-build pravanjan$ ps -ef | grep java.
  502  1296     1   0 12:20PM ??         0:43.98 /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java -XX:+HeapDumpOnOutOfMemoryError -Xmx1024m -Dfile.encoding=utf8 -Duser.country=IN -Duser.language=en -Duser.variant -cp /Users/pravanjan/.sdkman/candidates/gradle/current/lib/gradle-launcher-4.5.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 4.5
  502  1769     1   0 12:37PM ??         0:38.81 /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java -XX:+HeapDumpOnOutOfMemoryError -Xmx1024m -Dfile.encoding=utf8 -Duser.country=IN -Duser.language=en -Duser.variant -cp /Users/pravanjan/.sdkman/candidates/gradle/current/wrapper/dists/gradle-4.4-bin/bgaq7vklkazwgxox0hdadxbvi/gradle-4.4/lib/gradle-launcher-4.4.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 4.4
  502  1975     1   0 12:42PM ??         0:35.20 /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java -XX:+HeapDumpOnOutOfMemoryError -Xmx1024m -Dfile.encoding=UTF-8 -Duser.country=IN -Duser.language=en -Duser.variant -cp /Users/pravanjan/.sdkman/candidates/gradle/4.5/lib/gradle-launcher-4.5.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 4.5
  502  3546     1   0  1:19PM ??         0:34.61 /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -Xmx512m -Dfile.encoding=utf8 -Duser.country=IN -Duser.language=en -Duser.variant -cp /Users/pravanjan/.sdkman/candidates/gradle/current/wrapper/dists/gradle-5.0-bin/pu5208521seraqlersebvqk/gradle-5.0/lib/gradle-launcher-5.0.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 5.0
  502 17888 17849   0  2:25PM ??         0:13.03 /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -jar /Users/pravanjan/.vscode/extensions/redhat.java-0.45.0/server/plugins/org.eclipse.equinox.launcher_1.5.400.v20190514-1658.jar -configuration /Users/pravanjan/.vscode/extensions/redhat.java-0.45.0/server/config_mac -data /Users/pravanjan/Library/Application Support/Code/User/workspaceStorage/7b6fa3557a020a135d2853e05af4945a/redhat.java/jdt_ws
  502 18416 18406   0  3:48PM ??         0:12.69 /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java -XX:+HeapDumpOnOutOfMemoryError -Xmx1024m -Dfile.encoding=UTF-8 -Duser.country=IN -Duser.language=en -Duser.variant -cp /Users/pravanjan/.gradle/wrapper/dists/gradle-4.4-bin/bgaq7vklkazwgxox0hdadxbvi/gradle-4.4/lib/gradle-launcher-4.4.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 4.4
  502 18542  3043   0  3:55PM ttys001    0:00.00 grep java.
  502 18406 17836   0  3:48PM ttys002    0:04.48 /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java -Xdock:name=Gradle -Xdock:icon=/Users/pravanjan/gitProject/examples/typical-build/media/gradle.icns -Dorg.gradle.appname=gradlew -classpath /Users/pravanjan/gitProject/examples/typical-build/gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain goBuild

can you help me find the one which you are looking for? Thank you !!

**Comment by pravanjan** [comment]
[datadump.txt](https://github.com/gogradle/examples/files/3223386/datadump.txt)
Can you please check on this one?

**Comment by blindpirate** [comment]
```
"Task worker for ':' Thread 2" #39 prio=5 os_prio=31 tid=0x00007ff69a964000 nid=0x8a03 runnable [0x000070000aaac000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:94)
	at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1072)
	at java.nio.channels.FileChannel.lock(FileChannel.java:1053)
	at com.github.blindpirate.gogradle.core.cache.DefaultGlobalCacheManager$Session.<init>(DefaultGlobalCacheManager.java:83)
	at com.github.blindpirate.gogradle.core.cache.DefaultGlobalCacheManager$Session.<init>(DefaultGlobalCacheManager.java:71)
	at com.github.blindpirate.gogradle.core.cache.DefaultGlobalCacheManager.startSession(DefaultGlobalCacheManager.java:137)
```

Something seems to be not right. I notice you're using AdoptOpenJDK 8, my suggestion would be trying Oracle JDK 8. I've seen AdpotOpenJDK issues on such native methods.

I'll also try to reproduce it locally with AdoptOpenJDK8. Which version of AdoptOpenJDK8 are you using?

**Comment by pravanjan** [comment]
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b03, mixed mode)

Sure I don't prefer to use Oracle JDK, However, will give a try.

**Comment by blindpirate** [comment]
Thanks. I understand your preference of JDK. However I still can't reproduce it with my Mac 10.14.4 + AdoptOpenJDK 1.8.0_212-b03. Please let me know if things get resolved with Oracle JDK on your machine.

**Comment by pravanjan** [comment]
Oracle JDK 8 now its throws error on dependency

FAILURE: Build failed with an exception. -- 

* What went wrong:
Execution failed for task ':resolveBuildDependencies'.
> Exception in resolution, message is:
  Cannot resolve dependency:github.com/golang/example: commit='0dea2d0bf90754ffa40e0cb2f23b638f3e3d7e09', urls=[https://github.com/golang/example.git, git@github.com:golang/example.git]
  Resolution stack is:
  +- github.com/my/package


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by blindpirate** [comment]
You need to run with `--stacktrace` to get the stacktraces. Anyway, now it doesn't hang.

**Comment by pravanjan** [comment]
Yes, it does not hang on Oracle JDK.  I would be using AdoptopenJDK so this would not help.

**Comment by blindpirate** [comment]
I'm curious what's happening. Can you please rerun the build with `./gradlew goBuild --stacktrace` and put the stacktraces here?

**Comment by pravanjan** [comment]
Oracle JDK

typical-build pravanjan$ ./gradlew goBuild --stacktrace
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project : 
Found go 1.12.5 in /usr/local/go/bin/go, use it.

> Task :goPrepare 
Use project GOPATH: /Users/pravanjan/gitProject/examples/typical-build/.gogradle/project_gopath


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':resolveBuildDependencies'.
> Exception in resolution, message is:
  java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
  Resolution stack is:
  +- github.com/my/package


* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':resolveBuildDependencies'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: com.github.blindpirate.gogradle.core.exceptions.ResolutionStackWrappingException: Exception in resolution, message is:
java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
Resolution stack is:
+- github.com/my/package

        at com.github.blindpirate.gogradle.core.exceptions.ResolutionStackWrappingException.wrapWithResolutionStack(ResolutionStackWrappingException.java:51)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.resolve(DependencyTreeFactory.java:93)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.getTree(DependencyTreeFactory.java:44)
        at com.github.blindpirate.gogradle.task.ResolveDependencies.resolveDependencies(ResolveDependencies.java:170)
        at com.github.blindpirate.gogradle.task.ResolveDependencies.resolve(ResolveDependencies.java:151)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:780)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:747)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 29 more
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
        at com.github.blindpirate.gogradle.util.IOUtils.toByteArray(IOUtils.java:128)
        at com.github.blindpirate.gogradle.core.cache.DefaultGlobalCacheManager.getMetadataFromFile(DefaultGlobalCacheManager.java:244)
        at com.github.blindpirate.gogradle.core.cache.DefaultGlobalCacheManager.access$200(DefaultGlobalCacheManager.java:55)
        at com.github.blindpirate.gogradle.core.cache.DefaultGlobalCacheManager$Session.<init>(DefaultGlobalCacheManager.java:84)
        at com.github.blindpirate.gogradle.core.cache.DefaultGlobalCacheManager$Session.<init>(DefaultGlobalCacheManager.java:71)
        at com.github.blindpirate.gogradle.core.cache.DefaultGlobalCacheManager.startSession(DefaultGlobalCacheManager.java:137)
        at com.github.blindpirate.gogradle.core.dependency.resolve.AbstractVcsDependencyManager.doResolve(AbstractVcsDependencyManager.java:61)
        at com.github.blindpirate.gogradle.core.dependency.resolve.CacheEnabledDependencyResolverMixin.lambda$resolve$0(CacheEnabledDependencyResolverMixin.java:38)
        at com.github.blindpirate.gogradle.core.cache.CloneBackedCache.get(CloneBackedCache.java:34)
        at com.github.blindpirate.gogradle.core.cache.ProjectCacheManager.resolve(ProjectCacheManager.java:59)
        at com.github.blindpirate.gogradle.core.dependency.resolve.CacheEnabledDependencyResolverMixin.resolve(CacheEnabledDependencyResolverMixin.java:36)
        at com.github.blindpirate.gogradle.vcs.git.GitNotationDependency.doResolve(GitNotationDependency.java:28)
        at com.github.blindpirate.gogradle.core.dependency.AbstractNotationDependency.resolve(AbstractNotationDependency.java:55)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.createSubContextAndResolve(DependencyTreeFactory.java:102)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.lambda$resolve$0(DependencyTreeFactory.java:90)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.resolve(DependencyTreeFactory.java:91)
        ... 45 more


* Get more help at https://help.gradle.org

**Comment by blindpirate** [comment]
This is an issue fixed in latest release. I'll update all examples of this repo to `0.11.4`.

**Comment by pravanjan** [comment]
Thank you !!
